INSERT INTO departments(dep_name) VALUES ('Inpatient Service (IP)');
INSERT INTO departments(dep_name) VALUES ('Medical Department');
INSERT INTO departments(dep_name) VALUES ('Nursing Department');
INSERT INTO departments(dep_name) VALUES ('Paramedical Department');
INSERT INTO departments(dep_name) VALUES ('Physical Medicine and Rehabilitation Department');
INSERT INTO departments(dep_name) VALUES ('Pharmacy Department');
INSERT INTO departments(dep_name) VALUES ('Radiology Department (X-ray)');
INSERT INTO departments(dep_name) VALUES ('Dietary Department');
INSERT INTO departments(dep_name) VALUES ('Non-professional Services (Business Management)');
INSERT INTO departments(dep_name) VALUES ('Medical Record Department (MRD) and Personnel Department');
INSERT INTO departments(dep_name) VALUES ('Outpatient department (OPD)');
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Kathleen','Carter','Anesthesiology','1002334546', 2);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Charlene','Gonzales','Dermatology','1002334547', 3);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Debbie','Bernard','Diagnostic radiology','1002334548', 4);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Leslie','Butler','Emergency medicine','1002334549', 5);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Jacob','Torres','Family medicine','1002334550', 6);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Joshua','Lane','Internal medicine','1002334551', 7);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Jennifer','Gonzalez','Allergy and immunology','1002334552', 8);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Aimee','Smith','Anesthesiology','1002334553', 9);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Darren','Woods','Dermatology','1002334554', 10);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Kevin','Baker','Diagnostic radiology','1002334555', 11);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Robin','Dunn','Emergency medicine','1002334556', 1);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Melanie','Bishop','Family medicine','1002334557', 2);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Tracie','Acevedo','Internal medicine','1002334558', 3);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Maria','Kelly','Allergy and immunology','1002334559', 4);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Ruth','Roberts','Anesthesiology','1002334560', 5);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Kimberly','Rivera','Dermatology','1002334561', 6);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Robin','Williams','Diagnostic radiology','1002334562', 7);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Thomas','Curtis','Emergency medicine','1002334563', 8);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Tanya','Morales','Family medicine','1002334564', 9);
INSERT INTO doctors(first_name, last_name, specialty, pager_num, dep_id) VALUES ('Laurie','Cole','Internal medicine','1002334565', 10);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('David','Shepherd',1002334566,2);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Keith','King',1002334567,3);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('David','Hughes',1002334568,4);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Michael','Dawson',1002334569,5);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Cynthia','Snyder',1002334570,6);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Kimberly','Hooper',1002334571,7);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Richard','Williams',1002334572,8);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Carolyn','Reed',1002334573,9);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Mark','Huynh',1002334574,10);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Rachel','Kim',1002334575,11);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Michael','Wilson',1002334576,1);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Heather','Collins',1002334577,2);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Christopher','Miller',1002334578,3);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Maureen','Howard',1002334579,4);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Erika','Schmitt',1002334580,5);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Cameron','Moore',1002334581,6);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Jamie','Peters',1002334582,7);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Michael','Hammond',1002334583,8);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Casey','Douglas',1002334584,9);
INSERT INTO nurses(first_name, last_name, pager_num, dep_id) VALUES ('Melissa','Caldwell',1002334585,10);
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Abilify","Aripiprazole","https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/021436s044s045,021713s035s036,021729s027s028,021866s029s030lbl.pdf#page=77");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Abilify","Aripiprazole","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021436s043,021713s034,021729s026,021866s028lbl.pdf#page=84");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Abilify Maintena Kit","Aripiprazole","https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/202971s013lbl.pdf#page=52");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Abilify Mycite Kit","Aripiprazole","https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/207202s003lbl.pdf#page=44");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Abrilada","Adalimumab-Afzb","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/761118s000lbl.pdf#page=39");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Absorica","Isotretinoin","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021951s013lbl.pdf#page=32");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Abstral","Fentanyl Citrate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/022510s018lbl.pdf#page=29");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Accutane","Isotretinoin","http://www.accessdata.fda.gov/drugsatfda_docs/label/2010/018662s061MedGuide.pdf");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Aciphex","Rabeprazole Sodium","https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/020973s041lbl.pdf#page=34");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Aciphex Sprinkle","Rabeprazole Sodium","https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/204736s012lbl.pdf#page=21");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actemra","Tocilizumab","https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/125276s129,125472s042lbl.pdf#page=46");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actemra","Tocilizumab","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/125276s131lbl.pdf#page=49");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actemra","Tocilizumab","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/125472s044lbl.pdf#page=49");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Acthar Gel","Corticotropin","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/008372s068lbl.pdf#page=18");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actiq","Fentanyl Citrate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/020747s053lbl.pdf#page=43");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actonel","Risedronate Sodium","http://www.accessdata.fda.gov/drugsatfda_docs/label/2015/020835s048lbl.pdf#page=38");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actonel","Risedronate Sodium","http://www.accessdata.fda.gov/drugsatfda_docs/label/2019/020835s052lbl.pdf#page=38");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actonel With Calcium (Copackaged)","Calcium Carbonate; Risedronate Sodium","http://www.accessdata.fda.gov/drugsatfda_docs/label/2015/021823s011lbl.pdf#page=27");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actoplus MET","Metformin Hydrochloride; Pioglitazone Hydrochloride","https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/021842s022lbl.pdf#page=41");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actoplus MET XR","Metformin Hydrochloride; Pioglitazone Hydrochloride","https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/022024s014lbl.pdf#page=41");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Actos","Pioglitazone Hydrochloride","https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/021073s049lbl.pdf#page=35");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adasuve","Loxapine","https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/022549s006lbl.pdf#page=26");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall 10","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","http://www.fda.gov/downloads/Drugs/DrugSafety/UCM467750.pdf");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall 12.5","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","http://www.fda.gov/downloads/Drugs/DrugSafety/UCM467750.pdf");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall 15","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","http://www.fda.gov/downloads/Drugs/DrugSafety/UCM467750.pdf");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall 20","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","http://www.fda.gov/downloads/Drugs/DrugSafety/UCM467750.pdf");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall 30","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","http://www.fda.gov/downloads/Drugs/DrugSafety/UCM467750.pdf");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall 5","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","http://www.fda.gov/downloads/Drugs/DrugSafety/UCM467750.pdf");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall 7.5","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","http://www.fda.gov/downloads/Drugs/DrugSafety/UCM467750.pdf");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall XR 10","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021303s034lbl.pdf#page=24");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall XR 15","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021303s034lbl.pdf#page=24");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall XR 20","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021303s034lbl.pdf#page=24");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall XR 25","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021303s034lbl.pdf#page=24");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall XR 30","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021303s034lbl.pdf#page=24");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adderall XR 5","Amphetamine Aspartate; Amphetamine Sulfate; Dextroamphetamine Saccharate; Dextroamphetamine Sulfate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021303s034lbl.pdf#page=24");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Addyi","Flibanserin","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/022526s009lbl.pdf#page=23");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adempas","Riociguat","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/204819s015lbl.pdf#page=24");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adhansia XR","Methylphenidate Hydrochloride","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/212038s002lbl.pdf#page=25");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adlyxin","Lixisenatide","http://www.accessdata.fda.gov/drugsatfda_docs/label/2016/208471Orig1s000lbl.pdf#page=31");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adlyxin","Lixisenatide","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/208471s004lbl.pdf#page=24");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adzenys ER","Amphetamine","https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/204325s000lbl.pdf#page=26");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Adzenys XR-Odt","Amphetamine","http://www.accessdata.fda.gov/drugsatfda_docs/label/2017/204326s002mg.pdf");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Afrezza","Insulin Recombinant Human","https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/022472s011lbl.pdf#page=12");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Ambien","Zolpidem Tartrate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/019908s046lbl.pdf#page=23");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Ambien CR","Zolpidem Tartrate","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021774s027lbl.pdf#page=26");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Amjevita","Adalimumab-Atto","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/761024s004lbl.pdf#page=39");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Ampyra","Dalfampridine","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/022250s018lbl.pdf#page=13");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Anafranil","Clomipramine Hydrochloride","https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/019906s043lbl.pdf#page=27");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Anaprox","Naproxen Sodium","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/017581s115,018164s065,020067s024lbl.pdf#page=23");
INSERT INTO medications(med_name, med_type, common_use) VALUES ("Anaprox DS","Naproxen Sodium","https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/017581s115,018164s065,020067s024lbl.pdf#page=23");
INSERT INTO rooms VALUES (100,1,1);
INSERT INTO rooms VALUES (101,2,2);
INSERT INTO rooms VALUES (102,3,3);
INSERT INTO rooms VALUES (103,4,4);
INSERT INTO rooms VALUES (104,5,5);
INSERT INTO rooms VALUES (105,6,6);
INSERT INTO rooms VALUES (106,7,7);
INSERT INTO rooms VALUES (107,8,8);
INSERT INTO rooms VALUES (108,9,9);
INSERT INTO rooms VALUES (109,10,10);
INSERT INTO rooms VALUES (110,11,11);
INSERT INTO rooms VALUES (111,1,12);
INSERT INTO rooms VALUES (112,2,13);
INSERT INTO rooms VALUES (113,3,14);
INSERT INTO rooms VALUES (114,4,15);
INSERT INTO rooms VALUES (115,5,16);
INSERT INTO rooms VALUES (116,6,17);
INSERT INTO rooms VALUES (117,7,18);
INSERT INTO rooms VALUES (118,8,19);
INSERT INTO rooms VALUES (119,9,20);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Candace','Benton',101,2);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Timothy','Montgomery',102,3);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Jason','Cantrell',103,4);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Connie','Washington',104,5);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('David','Johnson',105,6);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Jessica','Lopez',106,7);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Jennifer','Garcia',107,8);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Shelby','Snyder',108,9);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Bryan','Sharp',109,10);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Mercedes','Wells',110,11);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Heather','Rodriguez',111,1);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Eric','Burch',112,2);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Zachary','Stewart',113,3);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('William','Andrews',114,4);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Cheryl','Burgess',115,5);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Kristi','Saunders',116,6);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Melissa','Taylor',117,7);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Alyssa','Wood',118,8);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('William','Bernard',119,9);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Justin','Bennett',100,10);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Trevor','Gonzales',101,11);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Laura','Fernandez',102,1);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Seth','Fields',103,2);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Christopher','Woodward',104,3);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Donald','Gutierrez',105,4);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Barbara','Stephenson',106,5);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Jillian','Lawson',107,6);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Charles','Calderon',108,7);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Veronica','Moyer',109,8);
INSERT INTO patients(first_name, last_name, r_number, dep_id) VALUES ('Alexis','Yoder',110,9);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Aagenaes syndrome","Abilify",2);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Aarskog–Ose–Pande syndrome","Abilify Maintena Kit",3);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Aarskog syndrome","Abilify Mycite Kit",4);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Aase–Smith syndrome","Abrilada",5);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Aase syndrome","Absorica",6);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("ABCD syndrome","Abstral",7);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Abdallat–Davis–Farrage syndrome","Accutane",8);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Abdominal aortic aneurysm","Aciphex",9);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Abdominal cystic lymphangioma","Aciphex Sprinkle",10);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Abdominal defects","Actemra",11);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Abdominal musculature absent microphthalmia joint laxity","Actemra",1);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Aberrant subclavian artery","Actemra",2);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Ablepharon macrostomia syndrome","Acthar Gel",3);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Abnormal systemic venous return","Actiq",4);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Abruzzo–Erickson syndrome","Actonel",5);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Absence of gluteal muscle","Actonel",6);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Absence of tibia with polydactyly","Actonel With Calcium (Copackaged)",7);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Absent corpus callosum cataract immunodeficiency","Actoplus MET",8);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Absent T lymphocytes","Actoplus MET XR",9);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Acanthocheilonemiasis","Actos",10);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Acanthocytosis","Adasuve",11);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Acanthocytosis chorea","Adderall 10",1);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Acanthosis nigricans","Adderall 12.5",2);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Acatalasemia","Adderall 15",3);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Accessory deep peroneal nerve","Adderall 20",4);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Accessory navicular bone","Adderall 30",5);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Accessory pancreas","Adderall 5",6);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achalasia","Adderall 7.5",7);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achalasia-Addisonianism-Alacrimia syndrome","Adderall XR 10",8);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achalasia alacrimia syndrome","Adderall XR 15",9);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achalasia","Adderall XR 20",10);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("familial esophageal","Adderall XR 25",11);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achalasia microcephaly","Adderall XR 30",1);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achard syndrome","Adderall XR 5",2);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achard–Thiers syndrome","Addyi",3);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Acheiropodia","Adempas",4);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achondrogenesis Kozlowski type","Adhansia XR",5);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achondrogenesis type 1A","Adlyxin",6);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achondrogenesis type 1B","Adlyxin",7);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achondrogenesis type 2","Adzenys ER",8);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achondroplasia Swiss type agammaglobulinemia","Adzenys XR-Odt",9);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achondroplastic dwarfism","Afrezza",10);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achromatopsia","Ambien",11);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Achromatopsia incomplete","Ambien CR",1);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("X-linked","Amjevita",2);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Acid maltase deficiency","Ampyra",3);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Acidemia","Anafranil",4);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("isovaleric","Anaprox",5);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("Acidemia","Anaprox DS",6);
INSERT INTO diagnoses(diag_name, treatment, dep_id) VALUES ("propionic","Androgel",7);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('A','F','1000','1100',2);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('B','G','1001','1101',3);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('C','H','1002','1102',4);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('D','I','1003','1103',5);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('E','J','1004','1104',6);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('F','K','1005','1105',7);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('G','L','1006','1106',8);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('H','M','1007','1107',9);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('I','N','1008','1108',10);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('J','O','1009','1109',11);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('K','P','1010','1110',12);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('L','Q','1011','1111',13);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('M','R','1012','1112',14);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('N','S','1013','1113',15);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('O','T','1014','1114',16);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('P','U','1015','1115',17);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('Q','V','1016','1116',18);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('R','W','1017','1117',19);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('S','X','1018','1118',20);
INSERT INTO visitors(first_name, last_name, time_in, time_out, p_id) VALUES ('T','Y','1019','1119',21);
INSERT INTO patient_doctor VALUES (1,1);
INSERT INTO patient_doctor VALUES (2,2);
INSERT INTO patient_doctor VALUES (3,3);
INSERT INTO patient_doctor VALUES (4,4);
INSERT INTO patient_doctor VALUES (5,5);
INSERT INTO patient_doctor VALUES (6,6);
INSERT INTO patient_doctor VALUES (7,7);
INSERT INTO patient_doctor VALUES (8,8);
INSERT INTO patient_doctor VALUES (9,9);
INSERT INTO patient_doctor VALUES (10,10);
INSERT INTO patient_doctor VALUES (11,11);
INSERT INTO patient_doctor VALUES (12,12);
INSERT INTO patient_doctor VALUES (13,13);
INSERT INTO patient_doctor VALUES (14,14);
INSERT INTO patient_doctor VALUES (15,15);
INSERT INTO patient_doctor VALUES (16,16);
INSERT INTO patient_doctor VALUES (17,17);
INSERT INTO patient_doctor VALUES (18,18);
INSERT INTO patient_doctor VALUES (19,19);
INSERT INTO patient_doctor VALUES (20,20);
INSERT INTO patient_doctor VALUES (21,1);
INSERT INTO patient_doctor VALUES (22,2);
INSERT INTO patient_doctor VALUES (23,3);
INSERT INTO patient_doctor VALUES (24,4);
INSERT INTO patient_doctor VALUES (25,5);
INSERT INTO patient_doctor VALUES (26,6);
INSERT INTO patient_doctor VALUES (27,7);
INSERT INTO patient_doctor VALUES (28,8);
INSERT INTO patient_doctor VALUES (29,9);
INSERT INTO patient_doctor VALUES (30,10);
INSERT INTO nurse_rooms VALUES (1,100);
INSERT INTO nurse_rooms VALUES (2,101);
INSERT INTO nurse_rooms VALUES (3,102);
INSERT INTO nurse_rooms VALUES (4,103);
INSERT INTO nurse_rooms VALUES (5,104);
INSERT INTO nurse_rooms VALUES (6,105);
INSERT INTO nurse_rooms VALUES (7,106);
INSERT INTO nurse_rooms VALUES (8,107);
INSERT INTO nurse_rooms VALUES (9,108);
INSERT INTO nurse_rooms VALUES (10,109);
INSERT INTO nurse_rooms VALUES (11,110);
INSERT INTO nurse_rooms VALUES (12,111);
INSERT INTO nurse_rooms VALUES (13,112);
INSERT INTO nurse_rooms VALUES (14,113);
INSERT INTO nurse_rooms VALUES (15,114);
INSERT INTO nurse_rooms VALUES (16,115);
INSERT INTO nurse_rooms VALUES (17,116);
INSERT INTO nurse_rooms VALUES (18,117);
INSERT INTO nurse_rooms VALUES (19,118);
INSERT INTO nurse_rooms VALUES (20,119);
INSERT INTO diagnosis VALUES (1,1);
INSERT INTO diagnosis VALUES (2,2);
INSERT INTO diagnosis VALUES (3,3);
INSERT INTO diagnosis VALUES (4,4);
INSERT INTO diagnosis VALUES (5,5);
INSERT INTO diagnosis VALUES (6,6);
INSERT INTO diagnosis VALUES (7,7);
INSERT INTO diagnosis VALUES (8,8);
INSERT INTO diagnosis VALUES (9,9);
INSERT INTO diagnosis VALUES (10,10);
INSERT INTO diagnosis VALUES (11,11);
INSERT INTO diagnosis VALUES (12,12);
INSERT INTO diagnosis VALUES (13,13);
INSERT INTO diagnosis VALUES (14,14);
INSERT INTO diagnosis VALUES (15,15);
INSERT INTO diagnosis VALUES (16,16);
INSERT INTO diagnosis VALUES (17,17);
INSERT INTO diagnosis VALUES (18,18);
INSERT INTO diagnosis VALUES (19,19);
INSERT INTO diagnosis VALUES (20,20);
INSERT INTO diagnosis VALUES (21,21);
INSERT INTO diagnosis VALUES (22,22);
INSERT INTO diagnosis VALUES (23,23);
INSERT INTO diagnosis VALUES (24,24);
INSERT INTO diagnosis VALUES (25,25);
INSERT INTO diagnosis VALUES (26,26);
INSERT INTO diagnosis VALUES (27,27);
INSERT INTO diagnosis VALUES (28,28);
INSERT INTO diagnosis VALUES (29,29);
INSERT INTO diagnosis VALUES (30,30);
INSERT INTO diagnosis VALUES (1,31);
INSERT INTO diagnosis VALUES (2,32);
INSERT INTO diagnosis VALUES (3,33);
INSERT INTO diagnosis VALUES (4,34);
INSERT INTO diagnosis VALUES (5,35);
INSERT INTO diagnosis VALUES (6,36);
INSERT INTO diagnosis VALUES (7,37);
INSERT INTO diagnosis VALUES (8,38);
INSERT INTO diagnosis VALUES (9,39);
INSERT INTO diagnosis VALUES (10,40);
INSERT INTO diagnosis VALUES (11,41);
INSERT INTO diagnosis VALUES (12,42);
INSERT INTO diagnosis VALUES (13,43);
INSERT INTO diagnosis VALUES (14,44);
INSERT INTO diagnosis VALUES (15,45);
INSERT INTO diagnosis VALUES (16,46);
INSERT INTO diagnosis VALUES (17,47);
INSERT INTO diagnosis VALUES (18,48);
INSERT INTO diagnosis VALUES (19,49);
INSERT INTO diagnosis VALUES (20,50);
INSERT INTO prescriptions VALUES (1,1);
INSERT INTO prescriptions VALUES (2,2);
INSERT INTO prescriptions VALUES (3,3);
INSERT INTO prescriptions VALUES (4,4);
INSERT INTO prescriptions VALUES (5,5);
INSERT INTO prescriptions VALUES (6,6);
INSERT INTO prescriptions VALUES (7,7);
INSERT INTO prescriptions VALUES (8,8);
INSERT INTO prescriptions VALUES (9,9);
INSERT INTO prescriptions VALUES (10,10);
INSERT INTO prescriptions VALUES (11,11);
INSERT INTO prescriptions VALUES (12,12);
INSERT INTO prescriptions VALUES (13,13);
INSERT INTO prescriptions VALUES (14,14);
INSERT INTO prescriptions VALUES (15,15);
INSERT INTO prescriptions VALUES (16,16);
INSERT INTO prescriptions VALUES (17,17);
INSERT INTO prescriptions VALUES (18,18);
INSERT INTO prescriptions VALUES (19,19);
INSERT INTO prescriptions VALUES (20,20);
INSERT INTO prescriptions VALUES (21,21);
INSERT INTO prescriptions VALUES (22,22);
INSERT INTO prescriptions VALUES (23,23);
INSERT INTO prescriptions VALUES (24,24);
INSERT INTO prescriptions VALUES (25,25);
INSERT INTO prescriptions VALUES (26,26);
INSERT INTO prescriptions VALUES (27,27);
INSERT INTO prescriptions VALUES (28,28);
INSERT INTO prescriptions VALUES (29,29);
INSERT INTO prescriptions VALUES (30,30);
INSERT INTO prescriptions VALUES (1,31);
INSERT INTO prescriptions VALUES (2,32);
INSERT INTO prescriptions VALUES (3,33);
INSERT INTO prescriptions VALUES (4,34);
INSERT INTO prescriptions VALUES (5,35);
INSERT INTO prescriptions VALUES (6,36);
INSERT INTO prescriptions VALUES (7,37);
INSERT INTO prescriptions VALUES (8,38);
INSERT INTO prescriptions VALUES (9,39);
INSERT INTO prescriptions VALUES (10,40);
INSERT INTO prescriptions VALUES (11,41);
INSERT INTO prescriptions VALUES (12,42);
INSERT INTO prescriptions VALUES (13,43);
INSERT INTO prescriptions VALUES (14,44);
INSERT INTO prescriptions VALUES (15,45);
INSERT INTO prescriptions VALUES (16,46);
INSERT INTO prescriptions VALUES (17,47);
INSERT INTO prescriptions VALUES (18,48);
INSERT INTO prescriptions VALUES (19,49);
INSERT INTO prescriptions VALUES (20,50);